/* Dekk Core Team
*
*
*
*
*
*/

#ifndef DEF_SANCTUM_OF_DOMINATION_H_
#define DEF_SANCTUM_OF_DOMINATION_H_

#include "CreatureAIImpl.h"

#define DataHeader "SOD"
#define SODScriptName "instance_sanctum_of_domination"

Position const SylvanasPlatformRevivePos = { 265.834f, -799.287f, 4104.977f, 3.811291f };

uint32 const EncounterCount = 10;

enum SanctumOfDominationDataTypes
{
    DATA_THE_TARRAGRUE = 0,
    DATA_THE_EYE_OF_THE_JAILER = 1,
    DATA_THE_NINE = 2,
    DATA_REMNANT_OF_NERZHUL = 3,
    DATA_SOULRENDER_DORMAZAIN = 4,
    DATA_PAINSMITH_RAZNAL = 5,
    DATA_GUARDIAN_OF_THE_FIRST_ONES = 6,
    DATA_FATESCRIBE_ROHKALO = 7,
    DATA_KELTHUZAD = 8,
    DATA_SYLVANAS_WINDRUNNER = 9,

    // Encounter-related data

    // Sylvanas Windrunner
    DATA_SYLVANAS_INTRODUCTION,
    DATA_SYLVANAS_INTRO,
    DATA_SYLVANAS_INTERMISSION_FINISH,
    DATA_BOLVAR_FORDRAGON_PINNACLE,
    DATA_JAINA_PROUDMOORE_PINNACLE,
    DATA_THRALL_PINNACLE,
    DATA_ANDUIN_CRUCIBLE,
    DATA_DOMINATION_ARROW,
    DATA_THRONE_OF_THE_DAMNED,

    DATA_SYLVANAS_SHADOWCOPY_RIDING,

    DATA_SYLVANAS_SHADOWCOPY_00 = 20,
    DATA_SYLVANAS_SHADOWCOPY_01,
    DATA_SYLVANAS_SHADOWCOPY_02,
    DATA_SYLVANAS_SHADOWCOPY_03,
    DATA_SYLVANAS_SHADOWCOPY_04,
    DATA_SYLVANAS_SHADOWCOPY_05,
    DATA_SYLVANAS_SHADOWCOPY_06,
    DATA_SYLVANAS_SHADOWCOPY_07,
    DATA_SYLVANAS_SHADOWCOPY_08,
    DATA_SYLVANAS_SHADOWCOPY_09,
    DATA_SYLVANAS_SHADOWCOPY_10,
    DATA_SYLVANAS_SHADOWCOPY_11
};

enum SanctumOfDominationCreatureIds
{
    // Bosses
    BOSS_SYLVANAS_WINDRUNNER = 175732,

    // Sylvanas Windrunner
    NPC_BOLVAR_FORDRAGON_PINNACLE = 178081,
    NPC_JAINA_PROUDMOORE_PINNACLE = 176533,
    NPC_THRALL_PINNACLE = 176532,
    NPC_ANDUIN_CRUCIBLE = 178072,

    NPC_SYLVANAS_SHADOWCOPY_RIDING = 178355,
    NPC_SYLVANAS_SHADOWCOPY_FIGHTER = 176369,
    NPC_SYLVANAS_JAILER_SOUL = 179262,

    NPC_DOMINATION_ARROW = 176920,
    NPC_THRONE_OF_THE_DAMNED = 180803,
};

enum SanctumOfDominationGameObjectIds
{
    GAMEOBJECT_TORGHAST_SPIKE_01 = 368743,
    GAMEOBJECT_TORGHAST_SPIKE_02 = 368744,
    GAMEOBJECT_TORGHAST_SPIKE_03 = 368745,
    GAMEOBJECT_TORGHAST_SPIKE_04 = 368746,
    GAMEOBJECT_TORGHAST_SPIKE_05 = 368747,
    GAMEOBJECT_TORGHAST_SPIKE_06 = 368748,
    GAMEOBJECT_TORGHAST_SPIKE_07 = 368749,
    GAMEOBJECT_TORGHAST_SPIKE_08 = 368750,
    GAMEOBJECT_TORGHAST_SPIKE_09 = 368751,
    GAMEOBJECT_TORGHAST_SPIKE_10 = 368752,
    GAMEOBJECT_TORGHAST_SPIKE_11 = 368753,
    GAMEOBJECT_TORGHAST_SPIKE_12 = 368754,
    GAMEOBJECT_INVISIBLE_WALL_PHASE_2 = 369242
};

enum SanctumOfDominationSpellIds
{
    SPELL_SYLVANAS_MODIFY_CHAMPIONS_FACTION = 355537
};

enum SanctumOfDominationEvents
{
    EVENT_RESET_PLAYERS_ON_SYLVANAS = 1
};

enum SanctumOfDominationActions
{
    ACTION_START_PHASE_TWO_ON_SYLVANAS = 20,
    ACTION_START_SYLVANAS_INTRODUCTION = 50
};

enum SanctumOfDominationAreas
{
    AREA_PINNACLE_OF_DOMINANCE = 13653,
    AREA_EDGE_OF_THE_ABYSS = 13654,
    AREA_THE_CRUCIBLE = 13655
};

enum SanctumofDominationWorldStates
{
    WORLD_STATE_SYLVANAS_ENCOUNTER_STARTED = 20346,
    WORLD_STATE_SYLVANAS_ENCOUNTER_COMPLETED = 20347,
    WORLD_STATE_SYLVANAS_ENCOUNTER_PHASE = 20348,
    WORLD_STATE_SYLVANAS_UNK_01 = 21210, // Sets to 0 several times on phase 3
    WORLD_STATE_SYLVANAS_UNK_02 = 21166, // Sets to 1 when SPELL_FINAL_SCENE is cast on players
    WORLD_STATE_SYLVANAS_UNK_03 = 21120, // Sets to 1 when 353687 spell is cast by NPC 179262
    WORLD_STATE_SYLVANAS_ACHIEVEMENT_COMPLETED = 21134,
    WORLD_STATE_SYLVANAS_UNK_04 = 20439, // This is always 1 on INIT and the following 0
    WORLD_STATE_SYLVANAS_UNK_05 = 20440,
    WORLD_STATE_SYLVANAS_UNK_06 = 20441,
    WORLD_STATE_SYLVANAS_UNK_07 = 20442,
    WORLD_STATE_SYLVANAS_UNK_08 = 20443
};

template <class AI, class T>
inline AI* GetSanctumOfDominationAI(T* obj)
{
    return GetInstanceAI<AI>(obj, SODScriptName);
}

#define RegisterSanctumOfDominationCreatureAI(ai_name) RegisterCreatureAIWithFactory(ai_name, GetSanctumOfDominationAI)

#endif
