#ifndef SHADOWLANDS_WORLD_BOSSES__H
#define SHADOWLANDS_WORLD_BOSSES__H

enum spells
{
    SPELL_ANTROS_DESTRUCTION_CORE    = 361341,
    SPELL_ANTROS_CONTROLLED_CALAMITY = 361169,
    SPELL_ANTROS_FURIOUS_SLAM        = 361209,

};

#endif // SHADOWLANDS_WORLD_BOSSES__H
