/*

*/

#ifndef DEF_SCENARIO_ZULDAZAR_H
#define DEF_SCENARIO_ZULDAZAR_H

enum Creatures
{
    NPC_KING_RASTAKHAN = 135890,

    NPC_BLOOD_CRAWG = 134433,
    NPC_BLOOD_HEXXER = 134432,
    NPC_BLOOD_TROLL = 134431,
    NPC_SIEGE_MONSTROSITY = 134507,
    NPC_BLOOD_TROLL_WARMOTHER = 134627,

    NPC_GENERAL_PURPOSE_BUNNY_ZTO = 72390,

    NPC_KRAGWA_THE_HUGE = 134469,
    NPC_PA_KU = 134493,

    NPC_SETHRAK_SKYCALLER = 134427,
    NPC_BLADESWORN_DIAMONDBACK = 134428,
    NPC_DIAMONDBACK_WARBRINGER = 134429,

    NPC_KING_RASTAKHAN_136324 = 136324,
    NPC_BWONSAMDI = 136352,
    NPC_RASTARI_SPIRIT = 136384,

    NPC_MADA_RENKALA = 142765,
};

enum CriteriaTrees
{
    CRITERIA_TREE_GATHER_YOUR_FORCES_AND_MOUNT_OLD_K_ZLOTEC                          = 65442,
    CRITERIA_TREE_DESTROY_THE_NAZMANI_INVADERS_IN_THE_SLIVER                         = 65558,
    CRITERIA_TREE_SECURE_THE_BRIDGE_TO_DAZAR_ALOR                                    = 65566,
    CRITERIA_TREE_RIDE_PA_KU_TO_THE_ZOCALO                                           = 65560,
    CRITERIA_TREE_RESCUE_THE_CIVILIANS_OF_THE_ZOCALO_AND_SLAY_THE_SETHRAK_ARMY_THERE = 65577,
    CRITERIA_TREE_JOIN_GONK_AND_HIS_PACK_AT_THE_BRIDGE_TO_DAZAR_ALOR                 = 65494,
    CRITERIA_TREE_FIND_KING_RASTAKHAN_AT_THE_ENTRANCE_TO_DAZAR_ALOR                  = 65972,
    CRITERIA_TREE_ASSAULT_DAZAR_ALOR_TO_REACH_ZUL_BEFORE_HE_CAN_DESTROY_THE_PYRAMID  = 65496,
};

enum ScenarioEvents
{
    SCENARIO_EVENT_MOUNT_OLD_K_ZLOTEC                                = 134460,
    SCENARIO_EVENT_BLOOD_TROLL_ARMY_SLAIN                            = 134431,
    SCENARIO_EVENT_SECURE_THE_BRIDGE_TO_DAZAR_ALOR                   = 134469,
    SCENARIO_EVENT_REACH_THE_ZOCALO                                  = 134493,

    SCENARIO_EVENT_CIVILIANS_RESCUED                                 = 134867,
    SCENARIO_EVENT_SETHRAK_SLAIN                                     = 134429,

    SCENARIO_EVENT_REACH_DAZAR_ALOR                                  = 134492,
    SCENARIO_EVENT_FIND_KING_RASTAKHAN_AT_THE_ENTRANCE_TO_DAZAR_ALOR = 63495,
    SCENARIO_EVENT_REACH_ZUL                                         = 142765,
};

enum Scenes
{
    SCENE_1 = 2045,
    SCENE_2 = 2055,
    SCENE_3 = 2084,
};

#endif
